# Generated by Django 2.2.10 on 2021-12-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20211216_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startedsurvey',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
